spring:
  application:
    name: initcat_user_service

  datasource:
    url: jdbc:mysql://XXX:3306/initcat?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: XXX
    password: XXX
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 10 #连接池中初始化的连接数
    minIdle: 10  #连接池中最小的连接数
    maxActive: 20 #连接池中最大连接数
    maxWait: 60000 #获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: 300000 #配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: SELECT 'x' FROM DUAL #验证连接用的sql
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat

server:
  port: 8081
  context-path: /user_service

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: XXX
      port: 6379
      password: XXX